[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
amd64 = { path = "../amd64" }

raw-cpuid = "^10.3.0"
acpi = "^4.1.0"
spin = "^0.9.2"
bitflags = "^1.3.2"

elf_rs = "^0.3.0"


[[bin]]
name = "kernel"
path = "src/init.rs"

[lib]
name = "sys"
path = "src/lib.rs"
