[package]
name = "kernel"
version = "0.1.0"
edition = "2021"


[dependencies]
amd64 = { path = "../amd64" }

uefi = "^0.12.0"
bitflags = "^1.3.2"
spin = "^0.9.2"

elf_rs = "^0.1.3"


[[bin]]
name = "kernel"
path = "src/init.rs"

[lib]
name = "libkernel"
path = "src/lib.rs"
