[package]
name = "bl"
version = "0.1.0"
edition = "2021"


[dependencies]
amd64 = { path = "../amd64" }
kernel = { path = "../kernel" }
uefi = { version = "^0.14.0", features = ["exts"] }
uefi-services = "^0.11.0"
log = "^0.4.14"
elf_rs = "^0.1.3"

# uart
bitflags = "1.3.2"
spin = "0.9.2"